[server]
http_port = 8080
grpc_port = 9090

[github]
repositories = [
    "https://github.com/gin-gonic/gin",
    "https://github.com/go-git/go-git"
]
token = "your_github_token_here"

[database]
path = "./data/repositories.db"

[log]
level = "info"